language: ruby
rvm:
  - 2.6.3
cache: bundler
before_script:
  - chmod +x ./cibuild/site
script: cibuild/site
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
notifications:
  email: false
deploy:
  provider: pages
  edge: true
  skip_cleanup: true
  cleanup: false
  keep_history: false
  local_dir: "./_site"
  commit_message: "release: deploy %{project_name}"
  github_token: $PAGES_TOKEN
  committer_from_gh: true
  on:
    branch: master
